#if SERVER
untyped
#endif

globalize_all_functions

array<vector> function GetNewFFADropShipLocations(string locationname, string mapname)
{
    array<vector> dropshiplocations

    if(mapname == "mp_rr_desertlands_64k_x_64k" || mapname == "mp_rr_desertlands_64k_x_64k_nx")
    {
        switch (locationname)
        {
            case "TTV Building":
                dropshiplocations.append(< 7321 , 3526 , -4179 > )
                dropshiplocations.append(< 7066 , 5574 , -4179 > )
                dropshiplocations.append(< 7382 , 7242 , -4179 > )
                dropshiplocations.append(< 8653 , 8244 , -4179 > )
                dropshiplocations.append(< 10677 , 7961 , -4179 > )
                dropshiplocations.append(< 11758 , 6751 , -3840 > )
                dropshiplocations.append(< 12856 , 5458 , -4179 > )
                dropshiplocations.append(< 12022 , 3499 , -4179 > )
                dropshiplocations.append(< 10466 , 2703 , -4179 > )
                dropshiplocations.append(< 8465 , 4230 , -4179 > )
                dropshiplocations.append(< 8191 , -6040 , -4179 > )
                dropshiplocations.append(< 10714 , 4777 , -4179 > )
                dropshiplocations.append(< 8957 , 6439 , -4179 > )
                dropshiplocations.append(< 9520 , 5630 , -3597 > )
                dropshiplocations.append(< 10548 , 5983 , -4179 > )
                dropshiplocations.append(< 8449 , 7370 , -4179 > )
                dropshiplocations.append(< 8919 , 6790 , -4179 > )
                dropshiplocations.append(< 11736 , 5410 , -3794 > )
                dropshiplocations.append(< 10198 , 8481 , -4179 > )
                dropshiplocations.append(< 9853 , 6523 , -4179 > )
                dropshiplocations.append(< 9858 , 4777 , -4179 > )
                dropshiplocations.append(< 8152 , 4795 , -4179 > )
                dropshiplocations.append(< 11141 , 4330 , -4179 > )
                dropshiplocations.append(< 10052 , 6965 , -4179 > )
                break;
            case "Skill trainer By Colombia":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "TTV Building 2":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Epicenter":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Lava Fissure":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Little Town 2":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Dome":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "TTV Building 3":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Space Elevator":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Capitol Buildings":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Little Town":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Overlook":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Refinery":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Factory":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Lava City":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Thermal Station":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
            case "Capitol City":
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                dropshiplocations.append(< 0 , 0 , 0 > )
                break;
        }
    }

    return dropshiplocations
}