global const table TRUE_TF2_SETTINGS = 
{
	//["acceleration"] = 10,
	["airacceleration"] = 500,
	//["airspeed"] = 60,
	["antiMultiJumpHeightFrac"] = 1,
	["automantle"] = 1,
	["automantle_enable"] = 1,
	["doublejump"] = 1,
	["gravityscale"] = 1.0,
	["impactSpeed"] = 380,
	["jumpheight"] = 120,
	["landslowdownduration"] = 0,
	["leech_range"] = 64,
	["skip_speed_reduce"] = 0,
	["Slidejumpheight"] = 90,
	["slideRequiredStartSpeed"] = 200,
	["slideSpeedBoostCap"] = 9999999,
	["slidedecel"] = 50,
	["slidevelocitydecay"] = 0.7,
	["stepheight"] = 18,
	["superjumpHorzSpeed"] = 180,
	["superjumpMaxHeight"] = 60,
	["superjumpMinHeight"] = 60,
	["wallrun"] = 1,
	["wallrunAccelerateHorizontal"] = 1500,
	["wallrunAccelerateVertical"] = 360,
	["wallrunJumpInputDirSpeed"] = 80,
	["wallrunJumpOutwardSpeed"] = 205,
	["wallrunJumpUpSpeed"] = 230,
	["wallrunMaxSpeedHorizontal"] = 420,
	["wallrunMaxSpeedVertical"] = 225,
	["wallrun_timeLimit"] = 1.75,
	["ziplineSpeed"]=600
}

global const table TRUE_TF2_SETTINGS_HIGH_AIRACCEL = 
{
	//["acceleration"] = 10,
	["airacceleration"] = 9000,
	//["airspeed"] = 60,
	["antiMultiJumpHeightFrac"] = 1,
	["automantle"] = 0,
	["automantle_enable"] = 0,
	["doublejump"] = 1,
	["gravityscale"] = 1.0,
	["impactSpeed"] = 380,
	["jumpheight"] = 120,
	["landslowdownduration"] = 0,
	["leech_range"] = 64,
	["skip_speed_reduce"] = 0,
	["Slidejumpheight"] = 90,
	["slideRequiredStartSpeed"] = 200,
	["slideSpeedBoostCap"] = 9999999,
	["slidedecel"] = 50,
	["slidevelocitydecay"] = 0.7,
	["stepheight"] = 18,
	["superjumpHorzSpeed"] = 180,
	["superjumpMaxHeight"] = 60,
	["superjumpMinHeight"] = 60,
	["wallrun"] = 1,
	["wallrunAccelerateHorizontal"] = 1500,
	["wallrunAccelerateVertical"] = 360,
	["wallrunJumpInputDirSpeed"] = 80,
	["wallrunJumpOutwardSpeed"] = 205,
	["wallrunJumpUpSpeed"] = 230,
	["wallrunMaxSpeedHorizontal"] = 420,
	["wallrunMaxSpeedVertical"] = 225,
	["wallrun_timeLimit"] = 1.75,
	["ziplineSpeed"]=600
}

global const table TRUE_TF2_SETTINGS_LOW_GRAV = 
{
	//["acceleration"] = 10,
	["airacceleration"] = 500,
	//["airspeed"] = 60,
	["antiMultiJumpHeightFrac"] = 1,
	["automantle"] = 1,
	["automantle_enable"] = 1,
	["doublejump"] = 1,
	["gravityscale"] = 0.5,
	["impactSpeed"] = 380,
	["jumpheight"] = 120,
	["landslowdownduration"] = 0,
	["leech_range"] = 64,
	["skip_speed_reduce"] = 0,
	["Slidejumpheight"] = 90,
	["slideRequiredStartSpeed"] = 200,
	["slideSpeedBoostCap"] = 9999999,
	["slidedecel"] = 50,
	["slidevelocitydecay"] = 0.7,
	["stepheight"] = 18,
	["superjumpHorzSpeed"] = 180,
	["superjumpMaxHeight"] = 60,
	["superjumpMinHeight"] = 60,
	["wallrun"] = 1,
	["wallrunAccelerateHorizontal"] = 1500,
	["wallrunAccelerateVertical"] = 360,
	["wallrunJumpInputDirSpeed"] = 80,
	["wallrunJumpOutwardSpeed"] = 205,
	["wallrunJumpUpSpeed"] = 230,
	["wallrunMaxSpeedHorizontal"] = 420,
	["wallrunMaxSpeedVertical"] = 225,
	["wallrun_timeLimit"] = 1.75,
	["ziplineSpeed"]=600
}

global const table CSGO_MOVEMENT = 
{
	["acceleration"] = 550,
	["airacceleration"] = 225,
	["airspeed"] = 30,
	["antiMultiJumpHeightFrac"] = 1,
	["automantle"] = 0,
	["automantle_enable"] = 0,
	["climbEnabled"] = 0,
	["climbheight"] = 0.1,
	["gravityscale"] = 1.25,
	["jumpheight"] = 55,
	["player_slideBoostEnabled"] = 0,
	["skip_speed_reduce"] = 0,
	["skip_time"] = 0,
	["slideRequiredStartSpeed"] = 9999999,
	["slideRequiredStartSpeedAir"] = 9999999,
	["slideSpeedBoost"] = 0,
	["slideSpeedBoostCap"] = 0,
	["slideVelocityDecay"] = 0,
	["superjumpMinHeight"] = 0,
	["wallrun"] = 0
}

global const table CSGO_MOVEMENT_HIGH_AIRACCEL = 
{
	["acceleration"] = 550,
	["airacceleration"] = 9000,
	["airspeed"] = 30,
	["antiMultiJumpHeightFrac"] = 1,
	["automantle"] = 0,
	["automantle_enable"] = 0,
	["climbEnabled"] = 0,
	["climbheight"] = 0.1,
	["gravityscale"] = 1.25,
	["jumpheight"] = 55,
	["player_slideBoostEnabled"] = 0,
	["skip_speed_reduce"] = 0,
	["skip_time"] = 0,
	["slideRequiredStartSpeed"] = 9999999,
	["slideRequiredStartSpeedAir"] = 9999999,
	["slideSpeedBoost"] = 0,
	["slideSpeedBoostCap"] = 0,
	["slideVelocityDecay"] = 0,
	["superjumpMinHeight"] = 0,
	["wallrun"] = 0
}

global const table SURF_SETTINGS = 
{
	["airacceleration"] = 6000,
	["acceleration"] = 10,
	["airspeed"] = 60
}

global const table HL1_MOVEMENT = 
{
	["acceleration"] = 550,
	["airacceleration"] = 1200,
	["airspeed"] = 30,
	["antiMultiJumpHeightFrac"] = 1,
	["automantle"] = 0,
	["automantle_enable"] = 0,
	["climbEnabled"] = 0,
	["climbheight"] = 0.1,
	["gravityscale"] = 1.25,
	["jumpheight"] = 55,
	["player_slideBoostEnabled"] = 0,
	["skip_speed_reduce"] = 0,
	["slideRequiredStartSpeed"] = 9999999,
	["slideRequiredStartSpeedAir"] = 9999999,
	["slideSpeedBoost"] = 0,
	["slideSpeedBoostCap"] = 0,
	["slideVelocityDecay"] = 0,
	["superjumpMinHeight"] = 0,
	["wallrun"]=0
}

global const table HALO_MOVEMENT = 
{
	["acceleration"] = 550,
	["airStrafeAcceleration"] = 0,
	["airStrafeEnabled"] = 0,
	["airStrafeTaperFinish"] = 0.01,
	["airStrafeTaperStart"] = 0.01,
	["airacceleration"] = 0,
	["airspeed"] = 0,
	["antiMultiJumpHeightFrac"] = 1,
	["automantle"] = 0,
	["automantle_enable"] = 0,
	["climbEnabled"] = 0,
	["climbheight"] = 0,
	["glideEnabled"] = 0,
	["glideRedirectJumpHeightFinishOffset"] = 0,
	["glideRedirectJumpHeightStartOffset"] = 0,
	["glideRedirectSideways"] = 0,
	["glideStrafe"] = 0,
	["glideStrafeTaperFinish"] = 0,
	["glideStrafeTaperStart"] = 0,
	["gravityscale"] = 0.7,
	["jumpheight"] = 65,
	["landslowdownduration"] = 0,
	["player_slideBoostEnabled"] = 0,
	["skip_speed_reduce"] = 0,
	["skip_time"] = 0,
	["slideRequiredStartSpeed"] = 9999999,
	["slideRequiredStartSpeedAir"] = 9999999,
	["slideSpeedBoost"] = 0,
	["slideSpeedBoostCap"] = 0,
	["slideVelocityDecay"] = 0,
	["superjumpCanUseAfterWallrun"] = 0,
	["superjumpMinHeight"] = 0,
	["wallrun"] = 0
}

global const table SUPERGLIDE_BOOST_SETTINGS = 
{
	["airacceleration"] = 1000,
	["player_slideBoostEnabled"] = 1,
	["player_slideBoostCooldown"] = 0.01,
	["slideRequiredStartSpeedAir"] = 0.01,
	["slideRequiredStartSpeed"]= 0.01,
	["slideSpeedBoostCap"] = 2500,
	["slideSpeedBoost"] = 2500
}

global const table INSTAGIB_PLAYER_SETTINGS = 
{
	["acceleration"] = 550,
	["airacceleration"] = 500, //3000
	["airspeed"] = 30,
	["automantle_enable"] = 1,
	["doublejump"] = 0,
	["gravityscale"] = 0.5,
	["impactSpeed"] = 380,
	["jumpheight"] = 150,
	["landslowdownduration"] = 0,
	["leech_range"] = 64,
	["slidedecel"] = 50,
	["slidevelocitydecay"] = 0.7,
	["stepheight"] = 18,
	["superjumpHorzSpeed"] = 180,
	["superjumpMaxHeight"] = 60,
	["superjumpMinHeight"] = 60,
	["wallrun"] = 0,
	["wallrunAccelerateHorizontal"] = 1500,
	["wallrunAccelerateVertical"] = 360,
	["wallrunJumpInputDirSpeed"] = 80,
	["wallrunJumpOutwardSpeed"] = 205,
	["wallrunJumpUpSpeed"] = 230,
	["wallrunMaxSpeedHorizontal"] = 420,
	["wallrunMaxSpeedVertical"] = 225,
	["wallrun_timeLimit"] = 1.75,
	["ziplineSpeed"] = 600
}

global const table HAVEFUN_PLAYER_SETTINGS = 
{
	["airacceleration"] = 3000,
	["airspeed"] = 1000,
	["automantle_enable"] = 1,
	["doublejump"] = 0,
	["gravityscale"] = 0.35,
	["impactSpeed"] = 380,
	["jumpheight"] = 1000,
	["landslowdownduration"] = 0,
	["leech_range"] = 64,
	["stepheight"] = 18,
	["ziplineSpeed"] = 600,
	["wallrun"] = 0,
	["slidedecel"] = 50,
	["slidevelocitydecay"] = 0.7,
	["sprintspeed"] = 1000,
	["speed"] = 800,
	["superjumpMinHeight"] = 60,
	["superjumpMaxHeight"] = 60,
	["superjumpHorzSpeed"] = 180,
	["wallrun_timeLimit"] = 1.75,
	["wallrunJumpOutwardSpeed"] = 205,
	["wallrunJumpUpSpeed"] = 230,
	["wallrunJumpInputDirSpeed"] = 80,
	["wallrunMaxSpeedVertical"] = 225,
	["wallrunMaxSpeedHorizontal"] = 420,
	["wallrunAccelerateVertical"] = 360,
	["wallrunAccelerateHorizontal"] = 1500
}