global function mp_rr_canyonlands_64k_x_64k_PathsPreprocess_Get

array<PathResult> function mp_rr_canyonlands_64k_x_64k_PathsPreprocess_Get()
{
        // Autogenerated from [LEVEL] > Map Paths Preprocess
        // There are 1 preprocessed paths in this function.
        // These paths are considered bidirectional.

        array<PathResult> paths

        PathResult pathResult0
        pathResult0.startPoint = <0, 0, 0>
        pathResult0.endPoint = <1000, 1000, 1000>
        pathResult0.path.append( <0, 0, 0> )
        pathResult0.path.append( <0, 0, 483.049133> )
        pathResult0.path.append( <0, 0, 1000> )
        pathResult0.path.append( <0, 0, 1319.07495> )
        pathResult0.path.append( <290.740753, 290.740753, 1226.30688> )
        pathResult0.path.append( <709.259399, 709.259399, 1092.76807> )
        paths.append( pathResult0 )
        return paths
}